# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Lane for distributing app using Firebase App Distributions"
    lane :distribute do
        gradle(task: "clean assembleRelease")
        firebase_app_distribution(
            service_credentials_file: "keys/firebase_credentials.json",
            app: ENV['FIREBASE_APP_ID'],
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
    end
end

desc "Creates a new debug build as bundle and extracts the universal apk to upload to firebase."
lane :buildDebug do |options|
  gradle(
    task: ":app:bundle",
    build_type:"Debug",
    flavor:options[:flavor],
    flags: "--no-daemon -Dkotlin.compiler.execution.strategy=in-proces --no-build-cache"
  )
  # call build_universal_apk.rb file which bundles and unzips the debug build
  # build_universal_apk
end

desc "Submit a new alpha build to Firebase App Distribution"
lane :deployToFirebase do |options|
  firebase_app_distribution(
      app: options[:app_id],
      groups: "FirebaseAppDistributionConfig/groups.txt",
      release_notes_file:"FirebaseAppDistributionConfig/release_notes.txt",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKENS'],
      android_artifact_type:"AAB",
      android_artifact_path: options[:build_output_path],
  )
end
