name: Develop trigger

on:
  push:
    branches: [develop]

jobs:
  check:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: generate commit logs
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "$branch_name"
          echo "DEVELOP_LATEST_COMMIT=$(git log $branch_name -1 --pretty=tformat:"  + %s")" >> $GITHUB_ENV

      - name: print latest commit
        run: |
          echo ${{ env.DEVELOP_LATEST_COMMIT }}
