name: Develop trigger

on:
  push:
    branches: [develop]

jobs:
  check:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: print commit logs
        run: |
          LATEST_COMMITS=$(git log --oneline -n 5 | awk '{$1=""; print $0}' | sed 's/^ *//')
          echo "${LATEST_COMMITS}"
