name: Develop trigger

on:
  push:
    branches: [develop]

jobs:
  check:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: generate commit logs
        run: |
          echo "ONE_LINE_TEXT_ENV_VAR=$(git log master -1 --pretty=tformat:"  + %s")" >> $GITHUB_ENV

      - name: Using the previously defined environment variable
        run: |
          echo ${{ env.ONE_LINE_TEXT_ENV_VAR }}
