# This is a workflow used for quick experiment purposes
name: Quick Experiment

on:
  workflow_dispatch:
    inputs:
      notes:
        description: 'Notes for this experiment (optional)'
        default: ''
        required: false
   
jobs:
  check:
     runs-on: [ ubuntu-latest ]
     
     steps:
      - name: Generate release notes
        run: |
            if [[ ${{ github.event.inputs.notes }} != '' ]]; then
              echo ${{ github.event.inputs.notes }}
            else
              echo echo ${GITHUB_REF##*/}
            fi
