# This is a workflow used for quick experiment purposes
name: Quick Experiment

on:
  workflow_dispatch:
   
jobs:
  check:
     runs-on: [ ubuntu-latest ]
     
     steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract branch name
        run: echo ${GITHUB_REF##*/}
