# This is a workflow used for quick experiment purposes
name: Quick Experiment

on:
  workflow_dispatch:
    inputs:
      notes:
        description: 'Notes for this experiment (optional)'
        default: ''
        required: false
   
jobs:
  check:
     runs-on: [ ubuntu-latest ]
     
     steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0

      - name: Generate release notes
        run: |
            echo ${GITHUB_REF}
            branch_name=${GITHUB_REF##*/}
            echo $branch_name
            develop_branch="develop"
            master_branch="master"
            if [[ "$branch_name" == "develop" || "$branch_name" == "master" || "$branch_name" == *"release/"* ]]; then
              echo $(git log -10 --pretty=%B)
            else
              echo "wrong branch"
            fi
