# This is a workflow that run ui tests on firebase test-lab
name: Run Tests

on: pull_request

jobs:
    generate-apk:
      name: Generate APK
      runs-on: ubuntu-latest

      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.10.0
          with:
              access_token: ${{ github.token }}

        - uses: actions/checkout@v3

        - name: Assemble app debug APK
          run: bundle exec fastlane buildAlphaBundle flavor:demo

        - name: Get Apk Path
          id: get-apk-path
          run: echo "::set-output name=apk-path::$(find . -name '*.apk' -print -quit)"

        - name: Upload app APK
          uses: actions/upload-artifact@v1
          with:
            name: app-debug
            path: ${{ steps.get-apk-path.outputs.apk-path }}

        - name: Assemble Android Instrumentation Tests
          run: bundle exec fastlane buildDebugAndroidTest flavor:demo

        - name: Get Android Test Apk Path
          id: get-android-test-apk-path
          run: echo "::set-output name=apk-path::$(find . -name '*androidTest.apk' -print -quit)"

        - name: Upload Android Test APK
          uses: actions/upload-artifact@v1
          with:
            name: app-debug-androidTest
            path: ${{ steps.get-android-test-apk-path.outputs.apk-path }}

    run-ui-test-on-firebase:
      name: Run UI test on firebase test-lab
      needs: generate-apk
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Download app APK
          uses: actions/download-artifact@v1
          with:
            name: app-debug

        - name: Download Android test APK
          uses: actions/download-artifact@v1
          with:
            name: app-debug-androidTest

        - name: Login to Google Cloud
          uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            version: '270.0.0'
            service_account_key: ${{ secrets.GCLOUD_AUTH_FIREBASE_SERVICE_ACCOUNT }}

        - name: Set current project
          run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

        - name: Run Instrumentation Tests in Firebase Test Lab
          run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait

