# This is a basic workflow that is manually triggered to deploy alpha build to firebase for testing
name: Test Deployment

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      flavor:
        description: 'Input flavor to build: demo, prod or both'
        default: 'both'
        required: true
      notes:
        description: 'Notes for this build (optional)'
        default: ''
        required: false
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2 # use latest version?
          bundler-cache: true

      - name: Build App For Both Demo and Production
        if: contains(github.event.inputs.flavor, 'both')
        run: 'bundle exec fastlane buildDebug flavor:demo && bundle exec fastlane buildDebug flavor:prod'

      - name: Build App For Demo
        if: contains(github.event.inputs.flavor, 'demo')
        run: 'bundle exec fastlane buildDebug flavor:demo'

      - name: Build App For Production
        if: contains(github.event.inputs.flavor, 'prod')
        run: 'bundle exec fastlane buildDebug flavor:prod'

      - name: Get App Path
        id: get-app-path
        run: echo "::set-output name=app-path::$(find . -name '*.aab' -print -quit)"

      - name: Deploy build to Firebase
        run: 'bundle exec fastlane deployToFirebase apk_path:app/build/outputs/bundle/debug/apks/universal.apk app_id:1:353599743826:android:c818eaef9bf8a1b00f3c8b'
        env:
          FIREBASE_CLI_TOKENS: ${{ secrets.FIREBASE_CLI_TOKENS }}